Args = --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=ch.qos.logback \
       --initialize-at-build-time=kotlin \
       --initialize-at-build-time=kotlinx.coroutines \
       -H:+UnlockExperimentalVMOptions
